# Generated by Django 5.0.7 on 2024-07-12 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "banner",
                    models.ImageField(
                        upload_to="challenges", verbose_name="Identidade visual"
                    ),
                ),
                ("rule", models.TextField(verbose_name="Regras")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de término"
                    ),
                ),
            ],
            options={
                "verbose_name": "Desafio",
                "verbose_name_plural": "Desafios",
            },
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenge.challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desafio do usuário",
                "verbose_name_plural": "Desafios dos usuários",
            },
        ),
    ]
