# Generated by Django 5.0.7 on 2024-07-13 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userchallenge",
            name="received_response",
            field=models.BooleanField(default=False, verbose_name="Recebeu resposta"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Desafio aceito"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenge",
                to="challenge.challenge",
                verbose_name="Desafio",
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
