# Generated by Django 5.0.7 on 2024-07-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchallenge",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_challenge",
                to="challenge.challenge",
            ),
        ),
    ]
