# Generated by Django 5.0.7 on 2024-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("password", models.CharField(max_length=150, verbose_name="Senha")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                ("phone", models.CharField(max_length=11, verbose_name="Telefone")),
            ],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
            },
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nome")),
                ("password", models.CharField(max_length=150, verbose_name="Senha")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                ("phone", models.CharField(max_length=11, verbose_name="Telefone")),
                (
                    "challenge",
                    models.ManyToManyField(
                        blank=True,
                        related_name="broker",
                        to="challenge.challenge",
                        verbose_name="Desafios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corretor",
                "verbose_name_plural": "Corretores",
            },
        ),
    ]
