# Generated by Django 5.0.7 on 2024-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
